name: Purge Cache and Check Response

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (UTC)
  workflow_dispatch: # Allow manual trigger

jobs:
  purge_and_check:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Perform PURGE Request and Check Response
      id: purge
      run: |
        RESPONSE=$(curl -s -X PURGE "https://camo.githubusercontent.com/your_url_here")
        echo "Response Body: $RESPONSE"
        
        # Use jq to parse the JSON response
        if echo "$RESPONSE" | jq -e '.status == "ok"' > /dev/null; then
          echo "Purge successful!"
        else
          echo "Error: Response did not contain 'status: ok'"
          exit 1
        fi
