name: Update Tryhackme

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (UTC)
  workflow_dispatch: # Allow manual trigger

jobs:
  purge_and_check:
    runs-on: ubuntu-latest

    steps:
    - name: Perform PURGE Request and Check Response
      id: purge
      run: |
        RESPONSE=$(curl -s -X PURGE "https://camo.githubusercontent.com/your_url_here")
        echo "Response Body: $RESPONSE"
        
        # Adjusted grep pattern to account for whitespace
        if echo "$RESPONSE" | grep -E -q '"status"[[:space:]]*:[[:space:]]*"ok"'; then
          echo "Purge successful!"
        else
          echo "Error: Response did not contain 'status: ok'"
          exit 1
        fi
